---
- name: Initial bootstrap
  hosts: all

  vars:
    disktype: sd
    base_packages:
      - htop
      - aptitude
      - bind9-utils
      - dnsutils
      - apache2
      - libapache2-mod-php7.4
      - php7.4-cli
      - php7.4-curl
      - php7.4-gd
      - php7.4-json
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-xml
      - composer
      - rabbitmq-server
      - prometheus
      - python3-pymysql
      - mariadb-client
  tasks:
    - name: Make www filesystem
      community.general.filesystem:
        fstype: ext4
        dev: "/dev/{{disktype}}b"
        opts: "-L app-www"
    - name: Create www mountpoint
      ansible.builtin.file:
        path: "/srv"
        state: directory
        mode: '0755'

    - name: Mount www disk
      ansible.posix.mount:
        path: "/srv"
        src: "LABEL=app-www"
        fstype: ext4
        state: mounted

    - name: Install packages
      apt:
        update_cache: yes
        name: "{{ base_packages }}"
      notify: Restart apache2

    - name: Enable the Apache2 modules
      community.general.apache2_module:
        state: present
        name: "{{ item }}"
      notify: Restart apache2
      loop:
        - headers
        - proxy
        - proxy_http
        - rewrite

    - name: Enable the Apache2 module
      community.general.apache2_module:
        state: present
        name: headers
      notify: Restart apache2
    
    - name: Remove default vhost
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent
      notify: Restart apache2
    
    - name: Deploy Prod vhost
      ansible.builtin.copy:
        src: production.conf
        dest: /etc/apache2/sites-enabled/production.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart apache2

    - name: Deploy Dev vhost
      ansible.builtin.copy:
        src: dev.conf
        dest: /etc/apache2/sites-enabled/dev.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart apache2

    - name: "Cron: nightly cleanup"
      ansible.builtin.cron:
        name: Nightly cleanup
        minute: "0"
        hour: "0"
        user: www-data
        job: "cd /srv/production/maintenance; php ClearOldData.php 2>&1 > /tmp/dataclearlog; php OldRequestCleanup.php 2>&1 > /tmp/oldreq-cleanup"
        cron_file: waca
    - name: "Cron: graph update"
      ansible.builtin.cron:
        name: Graph update
        minute: "*/5"
        user: www-data
        job: "/srv/dev/graph/update.sh > /tmp/graphupdlog 2>&1; /srv/dev/graph/graph.php > /tmp/graphlog 2>&1"
        cron_file: waca
    - name: "Cron: Job queue"
      ansible.builtin.cron:
        name: Job queue
        minute: "*/2"
        user: www-data
        job: "bash -l -c 'cd /srv/production/maintenance; php RunJobQueue.php &>/dev/null'"
        cron_file: waca
    - name: "Cron: Report link refresh"
      ansible.builtin.cron:
        name: Report link refresh
        hour: "11"
        minute: "0"
        user: www-data
        job: "cd /srv/dev/r; ./refresh.sh > /srv/dev/report/latesturls.txt"
        cron_file: waca

    - name: Enable RabbitMQ plugins
      community.rabbitmq.rabbitmq_plugin:
        names: rabbitmq_management,rabbitmq_shovel_management
        state: enabled
    
    - name: RabbitMQ users
      ansible.builtin.shell: 
        cmd: "{{ item }}"
      loop:
        - rabbitmqadmin declare user name=acc-prod password=changeme tags=
        - rabbitmqadmin declare permission vhost=/ user=acc-prod 'configure=^$' 'write=^acc\.notification$' 'read=^$'
        - rabbitmqadmin declare user name=shovel password=changeme tags=
        - rabbitmqadmin declare permission vhost=/ user=shovel 'configure=^$' 'write=^$' 'read=^acc\.notification\.queue$'
        - rabbitmqctl clear_password shovel

    - name: RabbitMQ configure policy
      ansible.builtin.shell: 
        cmd: "{{ item }}"
      loop:
        - >
          rabbitmqadmin declare policy name=notificationqueue pattern='^acc\.notification\.queue$' definition='{"dead-letter-exchange": "acc.deadletter", "max-length": 20, "message-ttl": 900000}' apply-to=queues

    - name: RabbitMQ exchanges
      ansible.builtin.shell: 
        cmd: "{{ item }}"
      loop:
        - rabbitmqadmin declare exchange name=acc.notification type=fanout durable=true
        - rabbitmqadmin declare exchange name=acc.deadletter type=fanout durable=true

    - name: RabbitMQ queues
      ansible.builtin.shell: 
        cmd: "{{ item }}"
      loop:
        - rabbitmqadmin declare queue name=acc.notification.queue durable=true
        - >
          rabbitmqadmin declare queue name=acc.deadletter.queue durable=true arguments='{"x-queue-mode": "lazy"}'

    - name: RabbitMQ notification binding
      community.rabbitmq.rabbitmq_binding:
        name: acc.notification
        destination: acc.notification.queue
        type: queue
        routing_key: ""

    - name: RabbitMQ deadletter binding
      community.rabbitmq.rabbitmq_binding:
        name: acc.deadletter
        destination: acc.deadletter.queue
        type: queue
        routing_key: ""

    - name: Prometheus configuration
      ansible.builtin.copy:
        content: |
          global:
            scrape_interval:     1m
            evaluation_interval: 1m
          rule_files:
          scrape_configs:
            - job_name: 'prometheus'
              metrics_path: '/prometheus/metrics'
              static_configs:
                - targets: ['localhost:9090']
            - job_name: acc
              static_configs:
                - targets: ['localhost:8080']
              metrics_path: '/other/prometheus.php'
        dest: /etc/prometheus/prometheus.yml
      notify: Restart prometheus
  handlers:
    - name: Restart apache2
      service:
        name: apache2
        state: restarted

    - name: Restart prometheus
      service:
        name: prometheus
        state: restarted
